# Workflow profile for mkseurat

# Conda settings
use-conda: True
conda-frontend: mamba

# General settings
verbose: False
keep-going: True
rerun-incomplete: True
latency-wait: 30
retries: 0

# Resource settings per rule
set-resources:
  create_seurat_object:
    threads: 1
    mem: "8GB"
    runtime: 30
  merge_captures:
    threads: 1
    mem: "32GB"
    runtime: 60
  attach_metadata:
    threads: 1
    mem: "16GB"
    runtime: 30
